### ISSUE TITLE
can not get metrics, "404 page not found"

### ISSUE THREAD

**Issue by dudumao520** [aauren/ntopng-exporter#1]
Hello everyone, I encountered an error, in the process of using this exporter,I think there is no problem with the configuration file, can you give me some suggestions? thank you very much！
==========================================================
**OS:Ubuntu 16.04 LTS**
-------------------------------------------------------------------------------
**Ntopng:**
v.4.2.210629    [Enterprise/Professional build]
GIT rev:        4.2-stable:44d80dd769ef6b00c1d8e6b440a4a260170859b9:20210629
Pro rev:        r3349
Built on:       Ubuntu 16.04.7 LTS
System Id:      29F0A0919206AAF2
Platform:       x86_64
Edition:        Enterprise L (Bundle)
License Type:   Time-Limited [Empty license file]
Validity:       Until Sun Jul 11 18:29:19 2021
----------------------------------------------------------------------------------------
**Exporter config** 
------------------------------------------------------------------------------------------
ntopng:
  endpoint: "http://192.168.1.200:3000"
  allowUnsafeTLS: false # set to true to accept self-signed or otherwise unverifiable certs from ntopng (default: false)
  user: admin
  password: 88888888
  authMethod: cookie # cookie, basic, or none are accepted values
  scrapeInterval: 15s # scrape from the ntopng API every x period of time (should be synced with your prometheus scrapes) (default: 1 minute)
  scrapeTargets: # you can also specify "all" as a single list item to scrape all available endpoints (default: all)
  - hosts
  - interfaces
  - l7protocols

host:
  interfacesToMonitor:
  - enp4s0

metric:
  localSubnetsOnly: # if this is defined, only include the local subnets defined here (greatly reduces number of metrics)
  - "192.168.1.0/24"
  excludeDNSMetrics: true # set to true, if you don't care about DNS metrics (also reduces number of metrics) (default: false)
  serve:
    ip: 0.0.0.0 # IP to serve metrics on, 0.0.0.0 is all interfaces (default: 0.0.0.0)
    port: 9876 # port to serve metrics on (default: 3001)
--------------------------------------------------------------------------------------
**Error**
-------------------------------------------------------------------------------
404 page not found

**Comment by dudumao520** [comment]
@aauren

**Comment by aauren** [comment]
@dudumao520 Its really hard to read the configuration file when its pasted as plain text. Can you please put the config file in a markdown code block?

Also helpful would be to know what URL you're hitting that gives the 404. To confirm, you need to use the `/metrics` path in order to get metrics from the exporter: https://github.com/aauren/ntopng-exporter/blob/f77a47683c8e35e34ed357669a89492e54b564cd/ntopng-exporter.go#L72

Finally, it would also be helpful to see any output from ntopng-exporter. It should just write it to stdout. Or if you run it as a systemd process it will be in the journal for the daemon.

**Comment by dudumao520** [comment]
> @dudumao520 Its really hard to read the configuration file when its pasted as plain text. Can you please put the config file in a markdown code block?
> 
> Also helpful would be to know what URL you're hitting that gives the 404. To confirm, you need to use the `/metrics` path in order to get metrics from the exporter:
> 
> https://github.com/aauren/ntopng-exporter/blob/f77a47683c8e35e34ed357669a89492e54b564cd/ntopng-exporter.go#L72
> 
> Finally, it would also be helpful to see any output from ntopng-exporter. It should just write it to stdout. Or if you run it as a systemd process it will be in the journal for the daemon.

ThankYou Very Very Very Much!!! Now Everything is normal now，thank you!
