### ISSUE TITLE
Issue reporting for other repositories

### ISSUE THREAD

**Issue by barnumbirr** [aauren/ntopng-exporter#13]
Hi,

I was wondering if "Issues" being disabled on your other repositories was by design? I've been playing around with aauren/rtorrent-exporter and have discovered a few bugs but can't report them in the repository itself. Same deal for aauren/rtorrent.

If you don't want to be bothered, feel free to close or ignore this issue.

Cheers!

**Comment by aauren** [comment]
Nope, not intentional. I’ve enabled it now.
