### ISSUE TITLE
See flows using those metrics

### ISSUE THREAD

**Issue by liorfranko** [aauren/ntopng-exporter#14]
Hi

Is there a way to add to `ntopng_host_bytes_sent` and `ntopng_host_bytes_rcvd` the source and destination IP and not only ip?
With that it will be possible to show the actual flows on a given interface.

Thanks!

**Comment by aauren** [comment]
This is technically possible, if we were to consume the flows API exposed by ntopng: https://www.ntop.org/guides/ntopng/api/rest/examples_v2.html#flows

Right now we only consume the interfaces and hosts APIs.

However, I don't think that there is a good way to expose this as a metric set in Prometheus. Exposing external IP addresses has the potential to greatly increase cardinality to the point that Prometheus would likely fall over as the label domain for IP addresses has a potential of `4294967296` values for just IPv4.

There are some good articles on this, but I'll put a few below:

* https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels
* https://newrelic.com/blog/how-to-relic/manage-prometheus-cardinality
