### ISSUE TITLE
analyze total bandwidth with latency

### ISSUE THREAD

**Issue by Azgar1998** [aauren/ntopng-exporter#5]
Hello,
I would like to know the total bandwidth with latency using the metrics, what do you recommend?
I do mirroring to recover network traffic
what is the default measurement? (bytes/s, kbits/s, etc.)

Thanks for your help

**Comment by aauren** [comment]
Hmm... bandwidth and latency are completely different measures, so you're never going to have an all in one metric from any measuring tool. Additionally ntopng doesn't really expose information about latency so there isn't a metric for us to produce here.

This tool just exposes metrics from ntopng. ntopng doesn't really measure total bandwidth, what it measures is flows and the traffic rates of those flows. If that's what you're trying to track, then this tool does that for you. For total bandwidth, really the only thing to do is to run a speed test.

As far as latency goes you could use something like ping_exporter which monitors latency using ICMP to different pre-defined targets: https://github.com/czerwonk/ping_exporter

As with all prometheus metrics, all of the units are bytes. Unit changes are done via graphing software like Grafana.

**Comment by Azgar1998** [comment]
Thanks to your reply.

Sorry, I expressed myself badly. I meant knowing the bandwidth currently used with the metrics. I tried with grafana but I have the impression that the values ​​do not correspond.

What metrics do you recommend for this?

**Comment by aauren** [comment]
Ahh... I see.

So flows are just an integer value of the number of flows that are currently happening.

If you want to get a sense of the throughput for a given flow then you want to use one of the `bytes` metrics from https://github.com/aauren/ntopng-exporter/blob/main/docs/ntopng_exporter_example_metrics.md

So for instance one of these 4 is probably what you're looking for:
* `ntopng_host_bytes_sent`
* `ntopng_host_bytes_rcvd`
* `ntopng_interface_bytes_sent`
* `ntopng_interface_bytes_rcvd`
* `ntopng_interface_current_throughput_bps`

Each one of those will have various labels on them that should help you narrow down a little bit more information about the traffic that is going through.

Configure your Grafana panel for the Y axis to be the unit of bytes (or in the case of the last one bytes per second) and then Grafana will do the rest of the unit conversions for you.

**Comment by Azgar1998** [comment]
Hello,
What suits me best is ntopng_interface_current_throughput_bps but I have a constant curve at 0, is this normal?

here is an example from prometheus:
![image](https://github.com/aauren/ntopng-exporter/assets/87006849/e2849c51-835d-4204-ac2a-f11b9b4472ac)

The other metrics work

Thanks,

Emmanuel PHILIPPEAU

**Comment by Azgar1998** [comment]
I just tested ntopng_host_bytes_rcvd and ntopng_host_bytes_send. it detects a significant transfer when this is not the case. What is going on ? Is there a specific configuration to do in ntopng_exporter?

here is an exemple from prometheus:
![image](https://github.com/aauren/ntopng-exporter/assets/87006849/63e76b06-42a1-42f9-ba27-75b408bb9e0d)

Ntopng does not see this transfer permanently. I did a test, I transferred a file, ntopng sees the transfer but not ntopng_exporter with metric  ntopng_host_bytes_rcvd and ntopng_host_bytes_send

Ntopng_exporter version: 1.1.1 (lastest)
ntopng version: 5.2.220414
OS: Ubuntu 22.04 

Regards,
Emmanuel PHILIPPEAU

**Comment by aauren** [comment]
You could be running into problems with your config, for instance, maybe the hosts that you're transferring to / from are not included in the subnet configuration or interface configuration of ntopng-exporter.

However, one of the low hanging fruits is that it doesn't look like you are graphing counts correctly in the above screenshots. Counts in Prometheus are monotonically increasing for a given dimension. That means that just graphing the metric as is, is almost never what you want, which is likely what you're doing according to the above screenshot. So you likely want to use a function around that metric like `increase` or `rate` along with a time duration.

A full example of this might be something like:

```
rate(ntopng_host_bytes_rcvd[5m])
```

It sounds like you're probably a bit new to Prometheus and time series data. I can help answer this one for you, but I'm not going to be able to give a full primer on time series metrics in a thread like this. I'd definitely recommend going through all of the Prometheus documentation, and / or maybe a book on Prometheus and time series data.
