### ISSUE TITLE
publish OCI image for v1.2.0

### ISSUE THREAD

**Issue by gberche-orange** [aauren/ntopng-exporter#6]
Thanks for sharing this great project ! I notice the v1.2.0 tag for release [v1.2.0](https://github.com/aauren/ntopng-exporter/releases/tag/v1.2.0) is not published on docker hub https://hub.docker.com/r/nresare/ntopng-exporter/tags

Is it published somewhere else ? 
If not, would it make sense to include the docker image build into the repo through a github workflow action ? 

Here is a sample similar workflow if ever this can help https://github.com/orange-cloudfoundry/kuttl-enriched-image/blob/master/.github/workflows/docker-publish.yml

Please, let me know if this may help to get a PR for setting up this pipeline.

Thanks in advance !

/CC @poblin-orange

**Comment by aauren** [comment]
Unfortunately, I don't have access to `nresare`'s docker hub repo. They were the original ones that contributed the Dockerfile and started building a docker image for ntopng-exporter.

However, I think that doing the container and goreleaser actions as part of GitHub actions is a good idea. So I changed it to publish to my namespace on dockerhub and you can now find it here: https://hub.docker.com/repository/docker/aauren/ntopng-exporter/general

The github actions all seem to be working now as of #7 

Thanks for the suggestion!

**Comment by gberche-orange** [comment]
great, thanks a lot !
